import type {ImageSourcePropType} from 'react-native';

export const images = {
  loaderScreen: require('./loader-screen.png') as ImageSourcePropType,
  loaderLogo: require('./loader-logo.png') as ImageSourcePropType,
  splashCanyoning: require('./splash-canyoning.png') as ImageSourcePropType,
  guideRope: require('./guide-rope.png') as ImageSourcePropType,
  guideMap: require('./guide-map.png') as ImageSourcePropType,
  guideCamera: require('./guide-camera.png') as ImageSourcePropType,
  guideTablet: require('./guide-tablet.png') as ImageSourcePropType,
  onboardingOne: require('./onboarding-one.png') as ImageSourcePropType,
  onboardingTwo: require('./onboarding-two.png') as ImageSourcePropType,
  onboardingThree: require('./onboarding-three.png') as ImageSourcePropType,
  onboardingFour: require('./onboarding-four.png') as ImageSourcePropType,
  niagaraFallsA: require('./granite-hollow.png') as ImageSourcePropType,
  niagaraFallsB: require('./emerald-cascade.png') as ImageSourcePropType,
  niagaraFallsC: require('./thunder-pass.png') as ImageSourcePropType,
  niagaraRiver: require('./silver-rapids.png') as ImageSourcePropType,
  trails: {
    whisperFalls: require('./granite-hollow.png') as ImageSourcePropType,
    graniteHollow: require('./emerald-cascade.png') as ImageSourcePropType,
    emeraldCascade: require('./silver-rapids.png') as ImageSourcePropType,
    shadowGorge: require('./thunder-pass.png') as ImageSourcePropType,
    silverRapids: require('./granite-hollow.png') as ImageSourcePropType,
    falconCanyon: require('./emerald-cascade.png') as ImageSourcePropType,
    crystalVeil: require('./silver-rapids.png') as ImageSourcePropType,
    ironCreek: require('./thunder-pass.png') as ImageSourcePropType,
    mossRidge: require('./granite-hollow.png') as ImageSourcePropType,
    thunderPass: require('./emerald-cascade.png') as ImageSourcePropType,
    cedarBasin: require('./silver-rapids.png') as ImageSourcePropType,
    ravenDrift: require('./thunder-pass.png') as ImageSourcePropType,
    blueTorrent: require('./granite-hollow.png') as ImageSourcePropType,
    goldenRift: require('./emerald-cascade.png') as ImageSourcePropType,
    wildCurrent: require('./silver-rapids.png') as ImageSourcePropType,
    mistValley: require('./thunder-pass.png') as ImageSourcePropType,
  },
};
